
---
services:
  mtr-junit-collector:
    image: ghcr.io/razvanliviuvarzaru/mtr-junit-collector:main
    restart: unless-stopped
    container_name: mtr-junit-collector
    hostname: mtr-junit-collector
    environment:
      - DATABASE_URL
      - GUNICORN_WORKERS
      - GUNICORN_HOST
      - GUNICORN_PORT
      - GUNICORN_LOGLEVEL
    network_mode: host
    healthcheck:
      test: ["CMD", "sh", "-c", "curl --fail http://$GUNICORN_HOST:$GUNICORN_PORT/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    logging:
      driver: journald
      options:
        tag: "bb-mtr-junit-collector"

